services:
  tensorrt-llm-model-builder:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./data:/data
      - ./src/job:/app/src/job
      - ~/.config/gcloud/application_default_credentials.json:/credentials.json
    environment:
      HF_TOKEN: "${HF_TOKEN}"
      ORGANIZATION: "meta-llama"
      BUCKET_NAME: "${BUCKET_NAME}"
      HUGGINGFACE_HUB_CACHE: "/data/"
      GCLOUD_PROJECT: "${GCLOUD_PROJECT}"
      MODEL_NAME: "Llama-3.1-8B-Instruct"
      GOOGLE_APPLICATION_CREDENTIALS: "/credentials.json"
    command: ["uv", "run", "main.py"]
